"use client";

import React, { useState, useEffect } from 'react';
import { 
  ArrowLeft, RefreshCw, Calendar, Sparkles, CheckCircle, 
  BookOpen, Clock, AlertTriangle, ChevronLeft, ChevronRight, Award
} from 'lucide-react';
import { apiGet } from '../../../lib/api';
import Link from 'next/link';

interface WeeklyDigest {
  user_id: string;
  compiled_date: string;
  attendance_summary: string;
  timetable_upcoming: string[];
  pending_fees: string;
  upcoming_events: string[];
  encouragement_message: string;
}

export default function WeeklyDigestPage() {
  const [digest, setDigest] = useState<WeeklyDigest | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeSlide, setActiveSlide] = useState(0);

  useEffect(() => {
    loadDigest();
  }, []);

  const loadDigest = async () => {
    setLoading(true);
    try {
      const profileStr = localStorage.getItem('iris_user_profile');
      let userId = 'u0000000-0000-0000-0000-000000000001';
      if (profileStr) {
        try {
          const prof = JSON.parse(profileStr);
          if (prof.id) userId = prof.id;
        } catch {}
      }

      const res = await apiGet(`/ai/digest/${userId}/latest`);
      if (res.success) {
        setDigest(res.digest);
      }
    } catch {
      // Sandbox fallback digest
      setDigest({
        user_id: 'mock_user',
        compiled_date: new Date().toISOString().split('T')[0],
        attendance_summary: 'Overall present rate is 84% (Present 42 out of 50 classes). Subject breakdown looks healthy except Electronics which sits at 71%.',
        timetable_upcoming: ['Maths Review (Monday 9:00 AM)', 'Physics Practicals (Tuesday 11:30 AM)', 'Data Structures Terminal (Wednesday 2:00 PM)'],
        pending_fees: 'You have a pending overdue fee statement of ₹2,500 library fines checkouts.',
        upcoming_events: ['HackOverflow 2026 (Wednesday)', 'CodeArena Arena Challenge (Friday)'],
        encouragement_message: 'Your overall attendance is very steady! Attend the upcoming Electronics lectures to satisfy compliance, and you are set for a stellar week. Keep pushing limits!'
      });
    } finally {
      setLoading(false);
    }
  };

  const nextSlide = () => {
    if (activeSlide < 4) setActiveSlide(prev => prev + 1);
  };

  const prevSlide = () => {
    if (activeSlide > 0) setActiveSlide(prev => prev - 1);
  };

  return (
    <main className="min-h-screen bg-[#0D0A1A] text-white pb-24 font-sans">
      {/* Header */}
      <div className="relative overflow-hidden border-b border-white/5 bg-[#13102A]/40 backdrop-blur-md">
        <div className="absolute top-0 right-0 w-96 h-96 bg-[#8B5CF6]/10 rounded-full blur-[120px]" />
        <div className="max-w-3xl mx-auto px-6 py-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div className="flex items-center gap-3">
            <Link href="/dashboard" className="p-2.5 rounded-xl bg-white/5 border border-white/5 hover:bg-white/10 transition-all text-[#C4B5FD]">
              <ArrowLeft className="w-4.5 h-4.5" />
            </Link>
            <div>
              <h1 className="font-extrabold text-2xl lg:text-3xl text-white">Weekly Campus Digest</h1>
              <p className="text-sm text-[#C4B5FD]/70">AI-compiled weekly Sunday review dossiers generated by Claude</p>
            </div>
          </div>
          
          <button 
            onClick={loadDigest}
            className="p-2.5 rounded-xl bg-white/5 border border-white/5 hover:bg-white/10 text-[#C4B5FD] transition-all flex items-center"
          >
            <RefreshCw className="w-4.5 h-4.5" />
          </button>
        </div>
      </div>

      <div className="max-w-xl mx-auto px-6 mt-12 space-y-6">
        
        {loading || !digest ? (
          <div className="py-24 text-center text-xs text-white/30 flex flex-col items-center justify-center">
            <RefreshCw className="w-8 h-8 animate-spin mb-3 text-[#A78BFA]" />
            Compiling campus metrics logs...
          </div>
        ) : (
          <div className="space-y-6">
            
            {/* Slide Indicators Progress Bar */}
            <div className="grid grid-cols-5 gap-1.5">
              {[0, 1, 2, 3, 4].map(idx => (
                <div 
                  key={idx} 
                  className={`h-1 rounded-full transition-all duration-300 ${
                    idx === activeSlide 
                      ? 'bg-[#8B5CF6] shadow-md shadow-violet-500/50' 
                      : idx < activeSlide 
                        ? 'bg-[#6C2BD9]/50' 
                        : 'bg-white/10'
                  }`}
                />
              ))}
            </div>

            {/* Slider cards container */}
            <div className="bg-[#13102A]/60 border border-white/5 p-8 rounded-3xl min-h-[340px] shadow-2xl relative flex flex-col justify-between overflow-hidden backdrop-blur-xl">
              <div className="absolute top-0 right-0 w-48 h-48 bg-[#8B5CF6]/5 rounded-full blur-3xl pointer-events-none" />

              {/* SLIDE 0: Attendance summary */}
              {activeSlide === 0 && (
                <div className="space-y-4 animate-in fade-in slide-in-from-right-3 duration-200">
                  <div className="flex items-center gap-2 text-xs font-bold text-[#A78BFA] uppercase tracking-wider">
                    <CheckCircle className="w-4.5 h-4.5" /> Weekly Attendance Review
                  </div>
                  <h3 className="font-extrabold text-xl leading-relaxed text-white">Your Present Rate Status</h3>
                  <p className="text-sm text-[#C4B5FD]/85 leading-relaxed pt-2">{digest.attendance_summary}</p>
                </div>
              )}

              {/* SLIDE 1: Upcoming Classes */}
              {activeSlide === 1 && (
                <div className="space-y-4 animate-in fade-in slide-in-from-right-3 duration-200">
                  <div className="flex items-center gap-2 text-xs font-bold text-[#A78BFA] uppercase tracking-wider">
                    <Clock className="w-4.5 h-4.5" /> Timetable Preview
                  </div>
                  <h3 className="font-extrabold text-xl leading-relaxed text-white">Next 3 Days Lectures</h3>
                  <div className="space-y-2.5 pt-2">
                    {digest.timetable_upcoming.map((c, i) => (
                      <div key={i} className="p-3 bg-[#0D0A1A] border border-white/5 rounded-2xl text-xs font-mono text-white/90">
                        {c}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* SLIDE 2: Pending Fees */}
              {activeSlide === 2 && (
                <div className="space-y-4 animate-in fade-in slide-in-from-right-3 duration-200">
                  <div className="flex items-center gap-2 text-xs font-bold text-[#A78BFA] uppercase tracking-wider">
                    <AlertTriangle className="w-4.5 h-4.5" /> Billing Exception Warning
                  </div>
                  <h3 className="font-extrabold text-xl leading-relaxed text-white">Bursar & Library Ledgers</h3>
                  <p className="text-sm text-[#C4B5FD]/85 leading-relaxed pt-2">{digest.pending_fees}</p>
                  <Link 
                    href="/student/fees"
                    className="inline-block mt-4 text-xs font-bold text-[#A78BFA] hover:text-white underline"
                  >
                    Resolve pending fees →
                  </Link>
                </div>
              )}

              {/* SLIDE 3: Upcoming Events */}
              {activeSlide === 3 && (
                <div className="space-y-4 animate-in fade-in slide-in-from-right-3 duration-200">
                  <div className="flex items-center gap-2 text-xs font-bold text-[#A78BFA] uppercase tracking-wider">
                    <Calendar className="w-4.5 h-4.5" /> Campus Activities
                  </div>
                  <h3 className="font-extrabold text-xl leading-relaxed text-white">Active Registrations & Events</h3>
                  <div className="space-y-2.5 pt-2">
                    {digest.upcoming_events.map((e, i) => (
                      <div key={i} className="p-3 bg-[#0D0A1A] border border-white/5 rounded-2xl text-xs font-bold text-white/90">
                        {e}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* SLIDE 4: AI Encouragement */}
              {activeSlide === 4 && (
                <div className="space-y-4 animate-in fade-in slide-in-from-right-3 duration-200">
                  <div className="flex items-center gap-2 text-xs font-bold text-[#A78BFA] uppercase tracking-wider">
                    <Sparkles className="w-4.5 h-4.5 text-amber-300" /> Weekly Mentorship Note
                  </div>
                  <h3 className="font-extrabold text-xl leading-relaxed text-white">Encouragement from IRIS</h3>
                  <p className="text-sm text-[#C4B5FD]/85 leading-relaxed pt-2 italic">"{digest.encouragement_message}"</p>
                  <div className="flex items-center gap-2 mt-4 text-xs text-white/40">
                    <Award className="w-4 h-4 text-amber-400" /> Compiled on Sunday 8:00 PM
                  </div>
                </div>
              )}

              {/* Navigation buttons */}
              <div className="flex justify-between items-center border-t border-white/5 pt-6 mt-8">
                <button
                  onClick={prevSlide}
                  disabled={activeSlide === 0}
                  className="p-2 rounded-xl bg-white/5 border border-white/5 hover:bg-white/10 disabled:opacity-20 text-[#C4B5FD] transition-all"
                >
                  <ChevronLeft className="w-5 h-5" />
                </button>

                <span className="text-xs font-mono text-white/30">
                  Slide {activeSlide + 1} of 5
                </span>

                <button
                  onClick={nextSlide}
                  disabled={activeSlide === 4}
                  className="p-2 rounded-xl bg-[#6C2BD9] hover:bg-[#8B5CF6] disabled:opacity-20 text-white transition-all shadow"
                >
                  <ChevronRight className="w-5 h-5" />
                </button>
              </div>

            </div>

          </div>
        )}

      </div>
    </main>
  );
}
